version: "3.8"

services:

  influxdb:
    restart: always
    image: influxdb
    network_mode: "host"
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=glances
      - INFLUXDB_RETENTION_ENABLED=true
      - INFLUXDB_RETENTION_CHECK_INTERVAL=30m
